DROP TABLE IF EXISTS Sectors;

CREATE TABLE IF NOT EXISTS Sectors (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  name VARCHAR(250) NOT NULL,
  value INT NOT NULL,
  level INT NOT NULL,
  parent_sector VARCHAR(250) DEFAULT NULL
);

INSERT INTO Sectors (name, value, level, parent_sector)
VALUES
('Manufacturing',1, 0, ''),
    ('Construction materials',19, 1, 'Manufacturing'),
    ('Electronics and optics',18, 1, 'Manufacturing'),
    ('Food and beverage',6, 1, 'Manufacturing'),
        ('Bakery & confectionery products',342, 2, 'Food and beverage'),
        ('Beverages',43, 2, 'Food and beverage'),
        ('Fish & fish products',42, 2, 'Food and beverage'),
        ('Meat & meat products',40, 2, 'Food and beverage'),
        ('Milk & dairy products',39, 2, 'Food and beverage'),
        ('Sweets & snack food',378, 2, 'Food and beverage'),
        ('Other (food & beverage)',437, 2, 'Food and beverage'),
    ('Furniture',13, 1, 'Manufacturing'),
        ('Bathroom/sauna',389, 2, 'Furniture'),
        ('Bedroom',385, 2, 'Furniture'),
        ('Children’s room',390, 2, 'Furniture'),
        ('Kitchen',98, 2, 'Furniture'),
        ('Living room',101, 2, 'Furniture'),
        ('Office',392, 2, 'Furniture'),
        ('Outdoor',341, 2, 'Furniture'),
        ('Project furniture',99, 2, 'Furniture'),
        ('Other (furniture)',394, 2, 'Furniture'),
    ('Machinery',12, 1, 'Manufacturing'),
        ('Machinery components',94, 2, 'Machinery'),
        ('Machinery equipment/tools',91, 2, 'Machinery'),
        ('Manufacture of machinery',224, 2, 'Machinery'),
        ('Maritime',97, 2, 'Machinery'),
            ('Aluminium & steel workboats',271, 3, 'Maritime'),
            ('Boat/yacht building',269, 3, 'Maritime'),
            ('Ship repair & conversion',230, 3, 'Maritime'),
        ('Metal structures',93, 2, 'Machinery'),
        ('Repair & maintenance service',227, 2, 'Machinery'),
        ('Other (machinery)',508, 2, 'Machinery'),
    ('Metalworking',11, 1, 'Manufacturing'),
        ('Construction of metal structures',67, 2, 'Metalworking'),
        ('Houses & buildings',263, 2, 'Metalworking'),
        ('Metal products',267, 2, 'Metalworking'),
        ('Metal works',542, 2, 'Metalworking'),
            ('CNC-machining',75, 3, 'Metal works'),
            ('Forgings, fasteners',62, 3, 'Metal works'),
            ('Gas/plasma/laser cutting',69, 3, 'Metal works'),
            ('MIG/TIG/aluminum welding',66, 3, 'Metal works'),
    ('Plastic & rubber',9, 1, 'Manufacturing'),
        ('Packaging',54, 2, 'Plastic & rubber'),
        ('Plastic goods',556, 2, 'Plastic & rubber'),
        ('Plastic processing technology',559, 2, 'Plastic & rubber'),
            ('Blowing',55, 3, 'Plastic processing technology'),
            ('Moulding',57, 3, 'Plastic processing technology'),
            ('Plastics welding and processing',53, 3, 'Plastic processing technology'),
        ('Plastic profiles',560, 2, 'Plastic & rubber'),
    ('Printing',5, 1, 'Manufacturing'),
        ('Advertising',148, 2, 'Printing'),
        ('Book/periodicals printing',150, 2, 'Printing'),
        ('Labelling & packaging printing',145, 2, 'Printing'),
    ('Textile & clothing',7, 1, 'Manufacturing'),
        ('Clothing',44, 2, 'Textile & clothing'),
        ('Textile',45, 2, 'Textile & clothing'),
    ('Wood',8, 1, 'Manufacturing'),
        ('Wooden building materials',51, 2, 'Wood'),
        ('Wooden houses',47, 2, 'Wood'),
        ('Other (wood)',337, 2, 'Wood'),
('Service',2, 0, ''),
    ('Business services',25, 1, 'Service'),
    ('Engineering',35, 1, 'Service'),
    ('Information Technology & Telecommunications',28, 1, 'Service'),
        ('Data processing, web portals, e-marketing',581, 2, 'Information Technology & Telecommunications'),
        ('Programming, consultancy',576, 2, 'Information Technology & Telecommunications'),
        ('Software, hardware',121, 2, 'Information Technology & Telecommunications'),
        ('Telecommunications',122, 2, 'Information Technology & Telecommunications'),
    ('Tourism',22, 1, 'Service'),
    ('Translation services',141, 1, 'Service'),
    ('Transport & logistics',21, 1, 'Service'),
        ('Air',111, 2, 'Transport & logistics'),
        ('Rail',114, 2, 'Transport & logistics'),
        ('Road',112, 2, 'Transport & logistics'),
        ('Water',113, 2, 'Transport & logistics'),
('Other',3, 0, ''),
    ('Creative industries',37, 1, 'Other'),
    ('Energy technology',29, 1, 'Other'),
    ('Environment',33, 1, 'Other')
;